### ISSUE TITLE
assembly built in debug mode.

### ISSUE THREAD

**Issue by DexterWoo** [iAJTin/iSMBIOS#3]
![image](https://user-images.githubusercontent.com/11514478/62852636-8fc07700-bd1c-11e9-85ba-e1dcaf35811d.png)
I was trying to use this in a UWP app that I am working on. and Windows App Cert kit give this message about iSMBIOS assemblies are built in debug mode. is there something wrong with the build pipeline?

**Comment by iAJTin** [comment]
Hi Dexter,

I have updated the nuget package to release mode, I understand that in this way you should not have problems,

**Comment by DexterWoo** [comment]
it's fixed now.  Thank you man.
