### ISSUE TITLE
bug in v1.1.2

### ISSUE THREAD

**Issue by DexterWoo** [iAJTin/iSMBIOS#7]
var structures = DMI.Instance.Structures;
                // type 0
        BiosVersion = GetSmbiosProperty(structures, DmiProperty.Bios.BiosVersion);

	private static string GetSmbiosProperty(DmiStructureCollection structure, IPropertyKey key)
        {
            string result = null;
           
            result = structure.GetProperty(key).ToString();
                
        
            return result;
        }

the first time structure.GetProperty was called, it will throw exception....

**Comment by DexterWoo** [comment]
Exception message:

System.InvalidCastException: Specified cast is not valid.
   at iTin.Core.Hardware.Specification.Dmi.DmiType000.PopulateProperties(DmiClassPropertiesTable properties)
   at iTin.Core.Hardware.Specification.Dmi.DmiBaseType`1.get_Properties()
   at iTin.Core.Hardware.Specification.Dmi.DmiStructureCollection.GetProperty(IPropertyKey propertyKey)
   at DeviceInformation.Smbios.SmbInformation.GetSmbiosProperty(DmiStructureCollection structure, IPropertyKey key)

**Comment by iAJTin** [comment]
Hi DexterWoo,

I have tried the case that you indicate to me on several computers, I attached an image and I do not obtain the exception that you indicate to me.

![Debug 2020-03-03 220757](https://user-images.githubusercontent.com/22968534/75820056-f7fba680-5d9b-11ea-9356-6c6bb55d9924.png)

If it gives you this exception, it can be:
Now iSMBIOS is more restrictive, I explain, the property you want to recover BiosVersion, as you indicate it belongs to the structure type 0 (BIOS) and the property is defined as of version 2.0 of this. (THIS IS NOW CHECKED).

Therefore, it may be that the type 0 structure you are evaluating does not comply with the 2.0 specification (which I think is very rare), but I comment because it is what it does functionally.

I think it explained to me well, on the other hand if you have the possibility to pass the byte array of the bios that you are evaluating, it could be more precise, since I cannot establish your scenario.

Greetings

**Comment by iAJTin** [comment]
Dexter,
I forgot, I attached the project that I used

[iSMBIOS.ConsoleAppCoreNuget.zip](https://github.com/iAJTin/iSMBIOS/files/4284047/iSMBIOS.ConsoleAppCoreNuget.zip)

**Comment by DexterWoo** [comment]
![image](https://user-images.githubusercontent.com/11514478/75891327-97876a80-5e6a-11ea-9ebc-0b3efe37e85e.png)

@iAJTin   I am seeing this exception while debugging the code you provided.

**Comment by DexterWoo** [comment]
Dumped the rawTable info as below.

0, 3, 1, 0, 74, 12, 0, 0, 222, 14, 0, 0, 1, 153, 0, 3, 16, 1, 32, 2, 48, 3, 77, 101, 109, 111, 114, 121, 32, 73, 110, 105, 116, 32, 67, 111, 109, 112, 108, 101, 116, 101, 0, 69, 110, 100, 32, 111, 102, 32, 68, 88, 69, 32, 80, 104, 97, 115, 101, 0, 66, 73, 79, 83, 32, 66, 111, 111, 116, 32, 67, 111, 109, 112, 108, 101, 116, 101, 0, 0, 14, 8, 1, 0, 1, 222, 0, 0, 73, 110, 116, 101, 108, 40, 82, 41, 32, 83, 105, 108, 105, 99, 111, 110, 32, 86, 105, 101, 119, 32, 84, 101, 99, 104, 110, 111, 108, 111, 103, 121, 0, 0, 16, 23, 2, 0, 3, 3, 3, 0, 0, 0, 2, 254, 255, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 40, 3, 0, 2, 0, 254, 255, 64, 0, 64, 0, 255, 127, 13, 0, 1, 2, 26, 128, 0, 107, 10, 3, 4, 5, 6, 2, 0, 128, 0, 0, 96, 9, 0, 0, 0, 0, 176, 4, 67, 104, 97, 110, 110, 101, 108, 65, 45, 68, 73, 77, 77, 48, 0, 66, 65, 78, 75, 32, 48, 0, 83, 97, 109, 115, 117, 110, 103, 0, 48, 51, 54, 55, 67, 48, 54, 57, 0, 78, 111, 110, 101, 0, 77, 52, 55, 49, 65, 52, 71, 52, 51, 77, 66, 49, 45, 67, 84, 68, 32, 32, 32, 32, 0, 0, 17, 40, 4, 0
, 2, 0, 254, 255, 64, 0, 64, 0, 255, 127, 13, 0, 1, 2, 26, 128, 0, 107, 10, 3, 4, 5, 6, 2, 0, 128, 0, 0, 96, 9, 0, 0, 0, 0, 176, 4, 67, 104, 97, 110, 110, 101, 108, 66, 45, 68, 73, 77, 77, 48, 0, 66, 65, 78, 75, 32, 50, 0, 83, 97, 109, 115, 117, 110, 103, 0, 48, 51, 54, 55, 67, 48, 68, 57, 0, 78, 111, 110, 101, 0, 77, 52, 55, 49, 65, 52, 71, 52, 51, 77, 66, 49, 45, 67, 84, 68, 32, 32, 32, 32, 0, 0, 19, 31, 5, 0, 0, 0, 0, 0, 255, 255, 255, 3, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 221, 12, 6, 0, 1, 1, 0, 2, 0, 0, 189, 16, 66, 73, 79, 83, 32, 71, 117, 97, 114, 100, 0, 0, 221, 26, 7, 0, 3, 1, 0, 7, 0, 86, 80, 0, 2, 0, 0, 0, 0, 198, 0, 3, 0, 1, 6, 0, 0, 0, 82, 101, 102, 101, 114, 101, 110, 99, 101, 32, 67, 111, 100, 101, 32, 45, 32, 67, 80, 85, 0, 117, 67, 111, 100, 101, 32, 86, 101, 114, 115, 105, 111, 110, 0, 84, 88, 84, 32, 65, 67, 77, 32, 118, 101, 114, 115, 105, 111, 110, 0, 0, 221, 26, 8, 0, 3, 1, 0, 7, 0, 86, 80, 0, 2, 0, 12, 0, 0, 10, 0, 3, 4, 12, 0, 32, 141, 5, 82, 101, 102, 101, 1
14, 101, 110, 99, 101, 32, 67, 111, 100, 101, 32, 45, 32, 77, 69, 0, 77, 69, 66, 120, 32, 118, 101, 114, 115, 105, 111, 110, 0, 77, 69, 32, 70, 105, 114, 109, 119, 97, 114, 101, 32, 86, 101, 114, 115, 105, 111, 110, 0, 67, 111, 114, 112, 111, 114, 97, 116, 101, 32, 83, 75, 85, 0, 0, 221, 82, 9, 0, 11, 1, 0, 7, 0, 86, 80, 0, 2, 3, 255, 255, 255, 255, 255, 4, 0, 255, 255, 255, 48, 0, 5, 0, 255, 255, 255, 48, 0, 6, 0, 2, 10, 0, 0, 0, 7, 0, 2, 0, 0, 0, 0, 8, 0, 9, 0, 0, 0, 0, 9, 0, 10, 0, 0, 0, 0, 10, 0, 7, 0, 0, 0, 0, 11, 0, 6, 0, 0, 0, 0, 12, 0, 7, 0, 0, 0, 0, 82, 101, 102, 101, 114, 101, 110, 99, 101, 32, 67, 111, 100, 101, 32, 45, 32, 67, 78, 76, 32, 80, 67, 72, 0, 80, 67, 72, 45, 67, 82, 73, 68, 32, 83, 116, 97, 116, 117, 115, 0, 68, 105, 115, 97, 98, 108, 101, 100, 0, 80, 67, 72, 45, 67, 82, 73, 68, 32, 79, 114, 105, 103, 105, 110, 97, 108, 32, 86, 97, 108, 117, 101, 0, 80, 67, 72, 45, 67, 82, 73, 68, 32, 78, 101, 119, 32, 86, 97, 108, 117, 101, 0, 79, 80, 82, 79, 77, 32, 45, 32, 82, 83, 84, 32, 45, 32, 82, 
65, 73, 68, 0, 67, 78, 76, 32, 80, 67, 72, 32, 72, 32, 65, 48, 32, 72, 115, 105, 111, 32, 86, 101, 114, 115, 105, 111, 110, 0, 67, 78, 76, 32, 80, 67, 72, 32, 72, 32, 65, 120, 32, 72, 115, 105, 111, 32, 86, 101, 114, 115, 105, 111, 110, 0, 67, 78, 76, 32, 80, 67, 72, 32, 72, 32, 66, 120, 32, 72, 115, 105, 111, 32, 86, 101, 114, 115, 105, 111, 110, 0, 67, 78, 76, 32, 80, 67, 72, 32, 76, 80, 32, 66, 48, 32, 72, 115, 105, 111, 32, 86, 101, 114, 115, 105, 111, 110, 0, 67, 78, 76, 32, 80, 67, 72, 32, 76, 80, 32, 66, 120, 32, 72, 115, 105, 111, 32, 86, 101, 114, 115, 105, 111, 110, 0, 67, 78, 76, 32, 80, 67, 72, 32, 76, 80, 32, 68, 120, 32, 72, 115, 105, 111, 32, 86, 101, 114, 115, 105, 111, 110, 0, 0, 221, 54, 10, 0, 7, 1, 0, 7, 0, 86, 80, 0, 2, 0, 0, 7, 1, 100, 0, 3, 0, 7, 0, 86, 80, 0, 4, 5, 255, 255, 255, 255, 255, 6, 0, 0, 0, 0, 12, 0, 7, 0, 0, 0, 0, 12, 0, 8, 0, 255, 255, 255, 255, 255, 82, 101, 102, 101, 114, 101, 110, 99, 101, 32, 67, 111, 100, 101, 32, 45, 32, 83, 65, 32, 45, 32, 83, 121, 115, 116, 101, 109
, 32, 65, 103, 101, 110, 116, 0, 82, 101, 102, 101, 114, 101, 110, 99, 101, 32, 67, 111, 100, 101, 32, 45, 32, 77, 82, 67, 0, 83, 65, 32, 45, 32, 80, 67, 73, 101, 32, 86, 101, 114, 115, 105, 111, 110, 0, 83, 65, 45, 67, 82, 73, 68, 32, 83, 116, 97, 116, 117, 115, 0, 68, 105, 115, 97, 98, 108, 101, 100, 0, 83, 65, 45, 67, 82, 73, 68, 32, 79, 114, 105, 103, 105, 110, 97, 108, 32, 86, 97, 108, 117, 101, 0, 83, 65, 45, 67, 82, 73, 68, 32, 78, 101, 119, 32, 86, 97, 108, 117, 101, 0, 79, 80, 82, 79, 77, 32, 45, 32, 86, 66, 73, 79, 83, 0, 0, 221, 12, 11, 0, 1, 1, 0, 4, 0, 0, 0, 0, 70, 83, 80, 32, 66, 105, 110, 97, 114, 121, 32, 86, 101, 114, 115, 105, 111, 110, 0, 0, 7, 27, 12, 0, 1, 128, 1, 0, 1, 0, 1, 32, 0, 32, 0, 0, 4, 5, 7, 0, 1, 0, 0, 0, 1, 0, 0, 76, 49, 32, 67, 97, 99, 104, 101, 0, 0, 7, 27, 13, 0, 1, 129, 1, 0, 4, 0, 4, 32, 0, 32, 0, 0, 5, 5, 5, 0, 4, 0, 0, 0, 4, 0, 0, 76, 50, 32, 67, 97, 99, 104, 101, 0, 0, 7, 27, 14, 0, 1, 130, 1, 0, 32, 0, 32, 32, 0, 32, 0, 0, 6, 5, 8, 0, 32, 0, 0, 0, 32, 0, 0, 76, 51, 32,
 67, 97, 99, 104, 101, 0, 0, 4, 48, 15, 0, 1, 3, 198, 2, 236, 6, 8, 0, 255, 251, 235, 191, 3, 135, 100, 0, 52, 8, 108, 7, 65, 60, 12, 0, 13, 0, 14, 0, 4, 5, 6, 4, 4, 8, 252, 0, 198, 0, 4, 0, 4, 0, 8, 0, 85, 51, 69, 49, 0, 73, 110, 116, 101, 108, 40, 82, 41, 32, 67, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 0, 73, 110, 116, 101, 108, 40, 82, 41, 32, 67, 111, 114, 101, 40, 84, 77, 41, 32, 105, 55, 45, 56, 54, 54, 53, 85, 32, 67, 80, 85, 32, 64, 32, 49, 46, 57, 48, 71, 72, 122, 0, 78, 111, 110, 101, 0, 78, 111, 110, 101, 0, 78, 111, 110, 101, 0, 0, 134, 13, 16, 0, 8, 5, 25, 32, 0, 0, 0, 0, 0, 0, 0, 0, 26, 17, 0, 1, 2, 0, 224, 3, 255, 128, 154, 9, 125, 0, 0, 18, 0, 3, 13, 1, 15, 1, 12, 32, 0, 76, 69, 78, 79, 86, 79, 0, 82, 48, 90, 69, 84, 51, 55, 87, 32, 40, 49, 46, 49, 53, 32, 41, 0, 49, 50, 47, 49, 49, 47, 50, 48, 49, 57, 0, 0, 1, 27, 18, 0, 1, 2, 3, 4, 204, 154, 3, 131, 113, 36, 178, 17, 168, 92, 163, 73, 36, 29, 84, 212, 6, 5, 6, 76, 69, 78, 79, 86, 79, 0, 50, 48, 81, 53, 90, 52, 80, 54, 85, 83, 0, 84, 
104, 105, 110, 107, 80, 97, 100, 32, 76, 52, 57, 48, 0, 80, 70, 49, 78, 75, 74, 56, 86, 0, 76, 69, 78, 79, 86, 79, 95, 77, 84, 95, 50, 48, 81, 53, 95, 66, 85, 95, 83, 77, 66, 95, 70, 77, 95, 84, 104, 105, 110, 107, 80, 97, 100, 32, 76, 52, 57, 48, 0, 84, 104, 105, 110, 107, 80, 97, 100, 32, 76, 52, 57, 48, 0, 0, 2, 15, 19, 0, 1, 2, 3, 4, 5, 9, 6, 0, 0, 10, 0, 76, 69, 78, 79, 86, 79, 0, 50, 48, 81, 53, 90, 52, 80, 54, 85, 83, 0, 83, 68, 75, 48, 74, 52, 48, 54, 57, 55, 32, 87, 73, 78, 0, 76, 49, 72, 70, 57, 51, 87, 48, 48, 49, 86, 0, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 0, 3, 22, 20, 0, 1, 10, 2, 3, 4, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 76, 69, 78, 79, 86, 79, 0, 78, 111, 110, 101, 0, 80, 70, 49, 78, 75, 74, 56, 86, 0, 78, 111, 32, 65, 115, 115, 101, 116, 32, 73, 110, 102, 111, 114, 109, 97, 116, 105, 111, 110, 0, 76, 69, 78, 79, 86, 79, 95, 77, 84, 95, 50, 48, 81, 53, 95, 66, 85, 95, 83, 77, 66, 95, 70, 77, 95, 84, 104, 1
05, 110, 107, 80, 97, 100, 32, 76, 52, 57, 48, 0, 0, 8, 9, 21, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 49, 0, 0, 8, 9, 22, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 50, 0, 0, 8, 9, 23, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 51, 0, 0, 8, 9, 24, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 52, 0, 0, 126, 9, 25, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 53, 0, 0, 126, 9, 26, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 54, 0, 0, 126, 9, 27, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 55, 0, 0, 126, 9, 28, 0, 1, 0, 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 56, 0, 0, 126, 9, 29, 0, 1, 0,
 2, 18, 16, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 85, 83, 66, 32, 57, 0, 0, 8, 9, 30, 0, 1, 0, 2, 11, 31, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 69, 116, 104, 101, 114, 110, 101, 116, 0, 0, 126, 9, 31, 0, 1, 0, 2, 11, 31, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 69, 116, 104, 101, 114, 110, 101, 116, 0, 0, 126, 9, 32, 0, 1, 0, 2, 7, 28, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 69, 120, 116, 101, 114, 110, 97, 108, 32, 77, 111, 110, 105, 116, 111, 114, 0, 0, 8, 9, 33, 0, 1, 0, 2, 255, 28, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 72, 100, 109, 105, 49, 0, 0, 126, 9, 34, 0, 1, 0, 2, 255, 28, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 72, 100, 109, 105, 50, 0, 0, 126, 9, 35, 0, 1, 0, 2, 255, 28, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 72, 100, 109, 105, 51, 0, 0, 126, 9, 36, 0, 1, 0, 2, 255, 28, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 68, 105, 
115, 112, 108, 97, 121, 80, 111, 114, 116, 49, 0, 0, 126, 9, 37, 0, 1, 0, 2, 255, 28, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 68, 105, 115, 112, 108, 97, 121, 80, 111, 114, 116, 50, 0, 0, 8, 9, 38, 0, 1, 0, 2, 31, 29, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 72, 101, 97, 100, 112, 104, 111, 110, 101, 47, 77, 105, 99, 114, 111, 112, 104, 111, 110, 101, 32, 67, 111, 109, 98, 111, 32, 74, 97, 99, 107, 49, 0, 0, 126, 9, 39, 0, 1, 0, 2, 31, 29, 78, 111, 116, 32, 65, 118, 97, 105, 108, 97, 98, 108, 101, 0, 72, 101, 97, 100, 112, 104, 111, 110, 101, 47, 77, 105, 99, 114, 111, 112, 104, 111, 110, 101, 32, 67, 111, 109, 98, 111, 32, 74, 97, 99, 107, 50, 0, 0, 9, 17, 40, 0, 1, 1, 1, 3, 1, 0, 0, 0, 2, 0, 0, 0, 0, 77, 101, 100, 105, 97, 32, 67, 97, 114, 100, 32, 83, 108, 111, 116, 0, 0, 9, 17, 41, 0, 1, 1, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 83, 105, 109, 67, 97, 114, 100, 32, 83, 108, 111, 116, 0, 0, 12, 5, 42, 0, 0, 0, 0, 13, 22, 43, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 1, 101, 110, 45, 85, 83, 0, 0, 22, 26, 44, 0, 1, 2, 0, 0, 3, 2, 221, 17, 92, 43, 4, 255, 92, 0, 118, 78, 5, 10, 0, 0, 0, 0, 70, 114, 111, 110, 116, 0, 83, 77, 80, 0, 48, 49, 65, 86, 52, 54, 53, 0, 48, 48, 46, 48, 48, 0, 76, 105, 80, 0, 0, 126, 26, 45, 0, 1, 2, 0, 0, 3, 2, 0, 0, 0, 0, 4, 255, 0, 0, 0, 0, 5, 10, 0, 0, 0, 0, 0, 0, 140, 15, 46, 0, 76, 69, 78, 79, 86, 79, 11, 9, 1, 1, 2, 49, 46, 49, 53, 32, 0, 49, 46, 49, 51, 32, 0, 0, 133, 5, 47, 0, 1, 75, 72, 79, 73, 72, 71, 73, 85, 67, 67, 72, 72, 73, 73, 0, 0, 135, 19, 48, 0, 84, 80, 7, 2, 66, 65, 89, 32, 73, 47, 79, 32, 4, 0, 0, 0, 0, 130, 20, 49, 0, 36, 65, 77, 84, 1, 1, 1, 1, 1, 165, 175, 2, 192, 0, 1, 0, 0, 0, 131, 64, 50, 0, 53, 0, 0, 0, 12, 0, 0, 0, 0, 0, 10, 0, 248, 0, 132, 157, 0, 0, 0, 0, 9, 192, 0, 0, 0, 0, 12, 0, 141, 5, 32, 0, 0, 0, 0, 0, 254, 0, 189, 21, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 118, 80, 114, 111, 0, 0, 0, 0, 0, 0, 24, 5, 51, 0, 34, 0, 0, 132, 7, 52, 0, 1, 216, 54, 0, 0, 18, 23, 53, 0, 3, 2, 2, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 
128, 0, 0, 0, 128, 0, 0, 21, 7, 54, 0, 5, 4, 3, 0, 0, 21, 7, 55, 0, 7, 4, 2, 0, 0, 131, 22, 56, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 84, 86, 84, 45, 69, 110, 97, 98, 108, 101, 109, 101, 110, 116, 0, 0, 136, 6, 57, 0, 90, 90, 0, 0, 15, 31, 58, 0, 114, 2, 0, 0, 16, 0, 4, 1, 38, 0, 0, 0, 240, 0, 0, 0, 1, 4, 2, 8, 4, 10, 0, 20, 0, 22, 0, 0, 0, 140, 15, 59, 0, 76, 69, 78, 79, 86, 79, 11, 7, 1, 1, 2, 82, 48, 90, 72, 84, 51, 51, 87, 0, 49, 53, 47, 48, 57, 47, 50, 48, 49, 57, 0, 0, 14, 8, 60, 0, 1, 219, 0, 0, 36, 77, 69, 73, 0, 0, 219, 106, 61, 0, 1, 4, 1, 69, 2, 0, 160, 6, 129, 16, 128, 48, 0, 0, 0, 0, 64, 0, 0, 1, 31, 0, 0, 201, 10, 64, 68, 2, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 3, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77, 69, 73, 49, 0, 77, 69, 73, 50, 0, 77, 69, 73, 51, 0, 77, 69, 73, 52, 0, 0, 135, 18,
 62, 0, 84, 80, 7, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 4, 255, 254, 0, 0

**Comment by iAJTin** [comment]
Thanks Dexter,

I will look at it as soon as I can and update (the error you are commenting is already fixed, change uploaded to the repository.),

Sorry for the inconvenience,

**Comment by iAJTin** [comment]
Nuget package updated

**Comment by DexterWoo** [comment]
verified. sorry I forgot to close the issue.
